version: "3.9"
services:
  app:
    build: .
    container_name: roshni-app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: roshni-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roshni
      MYSQL_USER: roshni
      MYSQL_PASSWORD: roshni
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
